services:
  - type: web
    name: crypto-portfolio-dashboard
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
    autoDeploy: true

databases:
  - name: postgres
    databaseName: crypto_portfolio
    user: portfolio_user